export type ForestClientLocationType = {
  clientNumber: string;
  locationCode: string;
  locationName: string;
  companyCode: string;
  address1: string;
  address2: string;
  address3: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
  businessPhone: string;
  homePhone: string;
  cellPhone: string;
  faxNumber: string;
  email: string;
  expired: string;
  trusted: string;
  returnedMailDate: string;
  comment: string;
};
