version: '3.9'

services:
  frontned:
    container_name: frontend
    environment:
      REACT_APP_NRSPARWEBAPP_VERSION: dev
      REACT_APP_SERVER_URL: "http://localhost:8090"
      REACT_APP_ORACLE_SERVER_URL: "http://localhost:8091"
      REACT_APP_KC_URL: https://test.loginproxy.gov.bc.ca/auth
      REACT_APP_KC_REALM: standard
      REACT_APP_KC_CLIENT_ID: seed-planning-test-4296
    ports:
      - "3000:3000"
    networks:
      - local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:3000" ]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  local:
    name: spar
