FROM node:18.16.0-alpine3.17
ENV PORT=3000

# Packages
RUN apk add --no-cache python3 g++ make

# User, port and Healthcheck
USER 1001
EXPOSE ${PORT}
HEALTHCHECK CMD wget --no-verbose --tries=1 --spider http://localhost:${PORT} || exit 1

# Start
WORKDIR /app
CMD ["sh", "-c", "yarn install --frozen-lockfile --prefer-offline && yarn start"]
