# Base and envar
FROM node:18-bullseye-slim
ENV PORT=3000

# Packages
RUN apt-get update && \
    apt-get install -y g++ make python3

# Port, health check and user
EXPOSE ${PORT}
HEALTHCHECK CMD wget --no-verbose --tries=1 --spider http://localhost:${PORT} || exit 1
USER 1001

# Start
WORKDIR /app
CMD yarn install --frozen-lockfile --prefer-offline && \
    yarn start
