apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ${NAME}-${ZONE}
parameters:
  - name: NAME
    description: Module name
    value: nr-spar-webapp
  - name: COMPONENT
    description: Component name
    value: frontend
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CPU_REQUEST
    value: 15m
  - name: CPU_LIMIT
    value: 30m
  - name: MEMORY_REQUEST
    value: 30Mi
  - name: MEMORY_LIMIT
    value: 50Mi
  - name: MIN_REPLICAS
    description: The minimum amount of replicas for the horizontal pod autoscaler.
    value: "3"
  - name: MAX_REPLICAS
    description: The maximum amount of replicas for the horizontal pod autoscaler.
    value: "5"
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: PROMOTE
    description: Image (namespace/name:tag) to promote/import
    value: bcgov/nr-spar-webapp/frontend:test
  - name: REACT_APP_SPAR_BUILD_VERSION
    description: Current sample app release version
    required: true
  - name: REACT_APP_SERVER_URL
    description: REACT_APP_SERVER_URL
    required: true
  - name: REACT_APP_NRSPARWEBAPP_VERSION
    description: REACT_APP_NRSPARWEBAPP_VERSION
    required: true
  - name: REACT_APP_KC_URL
    description: REACT_APP_KC_URL
    required: true
  - name: REACT_APP_KC_REALM
    description: REACT_APP_KC_REALM
    required: true
  - name: REACT_APP_KC_CLIENT_ID
    description: REACT_APP_KC_CLIENT_ID
    required: true
  - name: REACT_APP_ORACLE_SERVER_URL
    description: Oracle back-end api URL
    required: true
  - name: LOG_LEVEL
    description: Caddy log level (debug, info, warn, error, panic, fatal)
    value: "info"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${IMAGE_TAG}
          from:
            kind: DockerImage
            name: ${REGISTRY}/${PROMOTE}
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}-${ZONE}
            deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
        spec:
          containers:
            - image: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              securityContext:
                capabilities:
                  add: ["NET_BIND_SERVICE"]
              env:
                - name: REACT_APP_SPAR_BUILD_VERSION
                  value: ${REACT_APP_SPAR_BUILD_VERSION}
                - name: REACT_APP_SERVER_URL
                  value: ${REACT_APP_SERVER_URL}
                - name: REACT_APP_NRSPARWEBAPP_VERSION
                  value: ${REACT_APP_NRSPARWEBAPP_VERSION}
                - name: REACT_APP_KC_URL
                  value: ${REACT_APP_KC_URL}
                - name: REACT_APP_KC_REALM
                  value: ${REACT_APP_KC_REALM}
                - name: REACT_APP_KC_CLIENT_ID
                  value: ${REACT_APP_KC_CLIENT_ID}
                - name: REACT_APP_ORACLE_SERVER_URL
                  value: ${REACT_APP_ORACLE_SERVER_URL}
                - name: LOG_LEVEL
                  value: ${LOG_LEVEL}
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              readinessProbe:
                successThreshold: 1
                failureThreshold: 15
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 30
                timeoutSeconds: 10
              livenessProbe:
                successThreshold: 1
                failureThreshold: 15
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 10
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      ports:
        - name: 3000-tcp
          protocol: TCP
          port: 80
          targetPort: 3000
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      host: ${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}
      port:
        targetPort: 3000-tcp
      to:
        kind: Service
        name: ${NAME}-${ZONE}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: ${NAME}-${ZONE}-${COMPONENT}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-spar-frontend-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
