# Base and envars
FROM amazoncorretto:17-alpine
RUN mkdir /logs && chown 777 /logs
ENV LANG=en_CA.UTF-8 LANGUAGE=en_CA.UTF-8 LC_ALL=en_CA.UTF-8

RUN adduser --system spring
USER spring

# Workdir
WORKDIR /app

# Tests
COPY pom.xml .
COPY src .
COPY mvnw .
COPY .mvn ./.mvn

CMD ["./mvnw", \
  "--no-transfer-progress", \
  "clean", \
  "verify", \
  "package", \
  "checkstyle:checkstyle", \
  "-P", \
  "all-tests", \
  "sonar:sonar", \
  "-Dsonar.projectKey=nr-spar_backend", \
  "-Dsonar.coverage.jacoco.xmlReportPaths=target/coverage-reports/merged-test-report/jacoco.xml", \
  "-Dsonar.exclusions=**/coverage/**", \
  "--file", \
  "pom.xml" \
]