FROM maven:3.9.2-eclipse-temurin-17

ENV LANG en_CA.UTF-8
ENV LANGUAGE en_CA.UTF-8
ENV LC_ALL en_CA.UTF-8

# Workdir, port and healthcheck
WORKDIR /app
EXPOSE 8090
# HEALTHCHECK CMD curl -f http://localhost:8090/actuator/health | grep '"status":"UP"'
ENTRYPOINT ["./mvnw", "spring-boot:run"]
