version: '3.9'

services:
  backend:
    container_name: backend
    environment:
      NR_SPAR_BACKEND_VERSION: dev
      KEYCLOAK_REALM_URL: https://test.loginproxy.gov.bc.ca/auth/realms/standard
      POSTGRESQL_HOST: database
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: default
      FORESTCLIENTAPI_ADDRESS: https://nr-forest-client-api-prod.api.gov.bc.ca/api
      FORESTCLIENTAPI_KEY: ${FORESTCLIENTAPI_KEY}
      JAVA_OPTS: ${JAVA_OPTS}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 1m30s
      timeout: 3s
      retries: 3
      start_period: 40s
    hostname: backend
    ports:
      - "8090:8090"
    networks:
      - local
    build:
      context: .
      dockerfile: Dockerfile

networks:
  local:
    name: spar
