package ca.bc.gov.backendstartapi.report;

import java.math.BigDecimal;
import java.sql.Timestamp;
import lombok.Data;

/**
 * Jasper bean for the SPRR001 main band. Property names match the jrxml {@code <field name>}
 * attributes and are filled via {@code JRBeanCollectionDataSource}.
 */
@Data
public class Sprr001MainRow {
  private String dbName;
  private String seedlotNumber;
  private String toBeRegistrdInd;
  private String status;
  private String statusDesc;
  private String species;
  private String speciesDesc;
  private String geneticClass;
  private String seedlotSourceCode;
  private String seedlotSource;
  private String superiorPrvncInd;
  private String bcSource;
  private String clientAcronym;
  private String applicantClientLocn;
  private String clientName;
  private String applicantClientNumber;
  private String applicantsAddress;
  private String applicantEmailAddress;
  private BigDecimal collectionOrgUnit;
  private String collectionOrgUnitDesc;
  private String collectionLocnDesc;
  private String collectionProv;
  private String cfsAppendix;
  private String orchardId;
  private String orchardAddress;
  private BigDecimal effectivePopSize;
  private String gwAd;
  private String gwDfs;
  private String gwDfu;
  private String gwDfw;
  private String gwDsb;
  private String gwDsc;
  private String gwDsg;
  private String gwGvo;
  private String gwIws;
  private String gwWdu;
  private String gwWve;
  private String gwWwd;
  private BigDecimal radiusOfCollectionArea;
  private BigDecimal collectionElevation;
  private BigDecimal collectionElevationMin;
  private BigDecimal collectionElevationMax;
  private BigDecimal collectionLatDeg;
  private BigDecimal collectionLatMin;
  private BigDecimal collectionLatSec;
  private String collectionLatCode;
  private String collectionLatDesc;
  private BigDecimal collectionLongDeg;
  private BigDecimal collectionLongMin;
  private BigDecimal collectionLongSec;
  private String collectionLongCode;
  private String collectionLongDesc;
  private String captureMethod;
  private String spzOfCollectionArea;
  private String spzOfCollectionAreaDesc;
  private BigDecimal overrideCnt;
  private String geoArea;
  private String bgcZoneCode;
  private String bgcSubzoneCode;
  private String variant;
  private String collectionBgcInd;
  private String collectionSpzInd;
  private String collectionStartDate;
  private String collectionEndDate;
  private String collectionMethod;
  private String collectorAddress;
  private String coneCollectionMethodDesc;
  private String coneCollectionMethod2Code;
  private String coneCollectionMethodDesc2;
  private String nmbrTreesFromCode;
  private String nmbrTreesFromDesc;
  private BigDecimal noOfContainers;
  private BigDecimal volPerContainer;
  private BigDecimal clctnVolume;
  private String orchardComment;
  private String collectionClientAcronym;
  private String collectionCliNumber;
  private String collectionCliLocnCd;
  private String collectionClientName;
  private BigDecimal elevation;
  private BigDecimal minElevation;
  private String spz;
  private BigDecimal maxElevation;
  private BigDecimal minLatitudeDeg;
  private BigDecimal minLatitudeMinutes;
  private BigDecimal minLatitudeSec;
  private BigDecimal maxLatitudeDeg;
  private BigDecimal maxLatitudeMin;
  private BigDecimal maxLatitudeSec;
  private BigDecimal minLongitudeDeg;
  private BigDecimal minLongitudeMinutes;
  private BigDecimal minLongitudeSec;
  private BigDecimal maxLongitudeDeg;
  private BigDecimal maxLongitudeMin;
  private BigDecimal maxLongitudeSec;
  private String ownershipComment;
  private String interimAgencyAcronym;
  private String intermAgenctNumber;
  private String intermAgenctLocn;
  private String interimAgencyName;
  private String storageLocation;
  private String intermStrgStDate;
  private String intermStrgEndDate;
  private String intermFacilityCode;
  private String storageFacilityType;
  private String extractoryAgencyAcronym;
  private String extrctCliNumber;
  private String extrctCliLocnCd;
  private String extractoryAgencyName;
  private String extractionStDate;
  private String extractionEndDate;
  private String seedAgencyAcronym;
  private String seedStoreClientLocn;
  private String seedStoreClientNumber;
  private String seedAgencyClientName;
  private String temporaryStorageEndDate;
  private String temporaryStorageStartDate;
  private String createdByUser;
  private String createdDate;
  private String lastUpdatedByUser;
  private String lastUpdatedDate;
  private String submittedByUser;
  private String submittedByDate;
  private Timestamp declaration;
}
