WITH CTE_SPAR AS (
	SELECT DISTINCT
		SEEDLOT_NUMBER, 
		ORCHARD_ID ,
		'Y' as PRIMARY_IND,
		REVISION_COUNT
	FROM SEEDLOT 
	WHERE ORCHARD_ID IS NOT NULL
	AND SECONDARY_ORCHARD_ID != ORCHARD_ID
	UNION ALL 
	SELECT DISTINCT
		SEEDLOT_NUMBER, 
		SECONDARY_ORCHARD_ID as ORCHARD_ID,
		'N' as PRIMARY_IND,
		REVISION_COUNT
	FROM SEEDLOT 
	WHERE SECONDARY_ORCHARD_ID IS NOT NULL
	  AND SECONDARY_ORCHARD_ID != ORCHARD_ID
)
SELECT DISTINCT
	   seedlot_number, 
	   orchard_id,  
	   revision_count,
	   primary_ind,
	   'LEGACY SPAR' as entry_userid, -- NOT NULL IN DOWNSTREAM
	   'LEGACY SPAR' as update_userid -- NOT NULL IN DOWNSTREAM
FROM CTE_SPAR
--WHERE  ROWNUM < 11
ORDER BY seedlot_number

