WITH CTE_SPAR AS (
	SELECT  S.SEEDLOT_NUMBER, 
			S.CONE_COLLECTION_METHOD_CODE,
			C.DESCRIPTION as CONE_COLLECTION_METHOD_OTHER_DESC,
			S.REVISION_COUNT
	FROM SEEDLOT S, 
		CONE_COLLECTION_METHOD_CODE C
	WHERE S.CONE_COLLECTION_METHOD_CODE = C.CONE_COLLECTION_METHOD_CODE
	AND S.CONE_COLLECTION_METHOD_CODE IS NOT NULL 
)
SELECT seedlot_number, 
	   cone_collection_method_code,  
	   cone_collection_method_other_desc,  
	   revision_count,
	   'LEGACY SPAR' as entry_userid, -- NOT NULL IN DOWNSTREAM
	   'LEGACY SPAR' as update_userid -- NOT NULL IN DOWNSTREAM
FROM CTE_SPAR
--WHERE  ROWNUM < 11
ORDER BY seedlot_number




