export type AddActivityRequest = {
  riaKey: number;
  standardActivityId: string;
  activityTypeCd?: string;
  testCategoryCd?: string;
  associatedRiaKey?: number;
  plannedStartDate: string;
  plannedEndDate: string;
  revisedStartDate?: string;
  revisedEndDate?: string;
  activityDuration: number;
  activityTimeUnit: string;
  significantStatusIndicator?: boolean;
  processResultIndicator?: boolean;
  testResultIndicator?: boolean;
  requestSkey: number;
  requestId: string;
  itemId: string;
  vegetationState: string;
  seedlotNumber?: string;
  familyLotNumber?: string;
};
