apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: nr-spar
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: FORESTCLIENTAPI_KEY
    required: true
  - name: ORACLE_HOST
    description: Oracle database host
    value: nrcdb03.bcgov
  - name: ORACLE_PORT
    description: Oracle database port
    value: "1543"
  - name: ORACLE_SERVICE
    description: Oracle service name
    value: dbq01.nrs.bcgov
  - name: ORACLE_USER
    description: Oracle database username for API
    value: proxy_fsa_spar_sync_user
  - name: ORACLE_PASSWORD
    description: Oracle database password for API
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-oracle-api
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      oracle-host: ${ORACLE_HOST}
      oracle-password: ${ORACLE_PASSWORD}
      oracle-port: ${ORACLE_PORT}
      oracle-service: ${ORACLE_SERVICE}
      oracle-user: ${ORACLE_USER}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-backend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      forest-client-api-key: ${FORESTCLIENTAPI_KEY}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-spar-backend-network-security-policy
    spec:
      policyTypes:
        - Ingress
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-fluentbit-logs
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: "75Mi"
      storageClassName: netapp-file-standard
