---
apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: nr-spar
  - name: COMPONENT
    description: Component name
    value: database
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: ORG
    description: Organization name
    value: bcgov
  - name: CRONJOB_RESTORE_TAG
    description: Image tag for database restore cronjob; e.g. PR number, latest or prod
    value: prod

  ### Backup-Container starts here ###
  - name: BACKUP_COMPONENT
    description: BACKUP_COMPONENT name
    value: database-backup
  - name: "DATABASE_DEFAULT_PORT"
    description: "The configured port for the database service"
    value: "5432"
  - name: "BACKUP_STRATEGY"
    description: "The strategy to use for backups; for example daily, or rolling."
    required: true
    value: "rolling"
  - name: "BACKUP_DIR"
    description: "The name of the root backup directory"
    required: true
    value: "/backups/"
  - name: "NUM_BACKUPS"
    description: "The number of backup files to be retained.  Used for the `daily` backup strategy.  Ignored when using the `rolling` backup strategy."
    required: false
    value: "5"
  - name: "DAILY_BACKUPS"
    description: "The number of daily backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: "7"
  - name: "WEEKLY_BACKUPS"
    description: "The number of weekly backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: "4"
  - name: "MONTHLY_BACKUPS"
    displayName: "Number of Monthly Backups to Retain"
    description: "The number of monthly backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: "1"
  - name: "JOB_SERVICE_ACCOUNT"
    description: "Name of the Service Account To Exeucte the Job As."
    value: "default"
    required: true
  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    description: "The number of successful jobs that will be retained"
    value: "5"
    required: true
  - name: "FAILED_JOBS_HISTORY_LIMIT"
    description: "The number of failed jobs that will be retained"
    value: "2"
    required: true
  - name: "JOB_BACKOFF_LIMIT"
    description: "The number of attempts to try for a successful job outcome"
    value: "0"
  - description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Backup Volume Capacity
    name: DB_BACKUP_PVC_SIZE
    value: 100Mi
  - name: CRON_MINUTES
    description: Random number, 0-60, for scheduling cronjobs
    from: "[0-5]{1}[0-9]{1}"
    generate: expression
  - name: RANDOM_EXPRESSION
    description: Random expression to make sure deployments update
    from: "[a-zA-Z0-9]{32}"
    generate: expression
objects:
  ### Backup-Container starts here ###
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}-${ZONE}-${BACKUP_COMPONENT}
      labels:
        app: ${NAME}-${ZONE}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${DB_BACKUP_PVC_SIZE}"
      storageClassName: netapp-file-standard
  - kind: CronJob
    apiVersion: "batch/v1"
    metadata:
      name: ${NAME}-${ZONE}-${BACKUP_COMPONENT}
      labels:
        app: ${NAME}-${ZONE}
        cronjob: ${NAME}-${ZONE}
    spec:
      schedule: "${CRON_MINUTES} 8 * * *" # Run daily at 8:xx AM UTC
      concurrencyPolicy: "Replace"
      successfulJobsHistoryLimit: "${{SUCCESS_JOBS_HISTORY_LIMIT}}"
      failedJobsHistoryLimit: "${{FAILED_JOBS_HISTORY_LIMIT}}"
      jobTemplate:
        metadata:
          labels:
            app: ${NAME}-${ZONE}
            cronjob: ${NAME}-${ZONE}
        spec:
          backoffLimit: ${{JOB_BACKOFF_LIMIT}}
          template:
            metadata:
              labels:
                app: ${NAME}-${ZONE}
                cronjob: ${NAME}-${ZONE}
            spec:
              containers:
                - name: ${NAME}-${ZONE}
                  image: "bcgovimages/backup-container:latest"
                  command:
                    - "/bin/bash"
                    - "-c"
                    - "/backup.sh -1"
                  volumeMounts:
                    - mountPath: "${BACKUP_DIR}"
                      name: "backup"
                  env:
                    - name: BACKUP_DIR
                      value: "${BACKUP_DIR}"
                    - name: BACKUP_STRATEGY
                      value: "${BACKUP_STRATEGY}"
                      optional: true
                    - name: NUM_BACKUPS
                      value: "${NUM_BACKUPS}"
                      optional: true
                    - name: DAILY_BACKUPS
                      value: "${DAILY_BACKUPS}"
                      optional: true
                    - name: WEEKLY_BACKUPS
                      value: "${WEEKLY_BACKUPS}"
                      optional: true
                    - name: MONTHLY_BACKUPS
                      value: "${MONTHLY_BACKUPS}"
                      optional: true
                    - name: DATABASE_SERVICE_NAME
                      value: "${NAME}-${ZONE}-${COMPONENT}"
                    - name: DEFAULT_PORT
                      value: ${DATABASE_DEFAULT_PORT}
                    - name: POSTGRESQL_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: ${NAME}-${ZONE}-${COMPONENT}
                          key: database-name
                    - name: DATABASE_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${NAME}-${ZONE}-${COMPONENT}
                          key: database-user
                    - name: DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${NAME}-${ZONE}-${COMPONENT}
                          key: database-password
                    - name: S3_BUCKET
                      valueFrom:
                        secretKeyRef:
                          name: ${NAME}-${ZONE}-${BACKUP_COMPONENT}
                          key: s3-bucket
                    - name: S3_ENDPOINT
                      valueFrom:
                        secretKeyRef:
                          name: ${NAME}-${ZONE}-${BACKUP_COMPONENT}
                          key: s3-endpoint
                    - name: S3_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${NAME}-${ZONE}-${BACKUP_COMPONENT}
                          key: s3-password
                    - name: S3_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${NAME}-${ZONE}-${BACKUP_COMPONENT}
                          key: s3-user
              volumes:
                - name: backup
                  persistentVolumeClaim:
                    claimName: ${NAME}-${ZONE}-${BACKUP_COMPONENT}
              restartPolicy: "Never"
              terminationGracePeriodSeconds: 30
              activeDeadlineSeconds: 1600
              dnsPolicy: "ClusterFirst"
              serviceAccountName: "${JOB_SERVICE_ACCOUNT}"
              serviceAccount: "${JOB_SERVICE_ACCOUNT}"
