apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: nr-spar
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: DB_PASSWORD
    description: Password for the PostgreSQL connection user
    required: true
  - name: FORESTCLIENTAPI_KEY
    required: true
  - name: ORACLE_HOST
    description: Oracle database host
    value: nrcdb03.bcgov
    required: true
  - name: ORACLE_SERVICE
    description: Oracle service name
    value: dbq01.nrs.bcgov
  - name: ORACLE_PASSWORD
    description: Oracle database password for API
    required: true
  - name: ORACLE_USER
    description: Oracle database username for API
    value: proxy_fsa_spar_read_only_user
  - name: ORACLE_CERT_SECRET
    description: Oracle database keystore secret
    required: true
  - name: ORACLE_SYNC_PASSWORD
    description: Oracle database password for Sync
    required: true
  - name: ORACLE_SYNC_USER
    description: Oracle database username for Sync
    value: proxy_fsa_spar_sync_user
  - name: VITE_USER_POOLS_WEB_CLIENT_ID
    description: Cognito user pools web client ID
    required: true
  - name: WEBHOOK_URL
    displayName: Webhook URL
    description: The URL of the webhook to use for notifications.  If not specified, the webhook integration feature is disabled.
    required: false
    value: ""
  - name: WEBHOOK_URL_HOST
    displayName: Webhook URL Hostname
    description: Webhook URL Hostname.  The backup-deploy.overrides.sh will parse this from the supplied WEBHOOK_URL, and fetch it from a secret for updates.
    required: false
    value:
  - name: FTP_SECRET_KEY
    displayName: FTP Secret Key
    description: The FTP secret key is used to wire up the credentials associated to the FTP.
    required: false
    value: ftp-secret
  - name: FTP_URL
    displayName: FTP Server URL
    description: The URL of the backup FTP server
    required: false
    value: ""
  - name: FTP_URL_HOST
    displayName: Ftp URL Hostname
    description: Ftp URL Hostname.  The backup-deploy.overrides.sh will parse this from the supplied FTP_URL, and fetch it from a secret for updates.
    required: false
    value:
  - name: FTP_USER
    displayName: FTP user name
    description: FTP user name
    required: false
    value: ""
  - name: FTP_PASSWORD
    displayName: FTP password
    description: FTP password
    required: false
    value: ""
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-database
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-name: ${NAME}
      database-password: ${DB_PASSWORD}
      database-port: "5432"
      database-user: ${NAME}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-oracle-api
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      oracle-host: ${ORACLE_HOST}
      oracle-password: ${ORACLE_PASSWORD}
      oracle-service: ${ORACLE_SERVICE}
      oracle-user: ${ORACLE_USER}
      oracle-secret: ${ORACLE_CERT_SECRET}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-sync
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      oracle-host: ${ORACLE_HOST}
      oracle-service: ${ORACLE_SERVICE}
      oracle-sync-password: ${ORACLE_SYNC_PASSWORD}
      oracle-sync-user: ${ORACLE_SYNC_USER}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-backend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      forest-client-api-key: ${FORESTCLIENTAPI_KEY}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-frontend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      vite-user-pools-web-client-id: ${VITE_USER_POOLS_WEB_CLIENT_ID}
  --
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-backup-webhook
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      webhook-url: ${WEBHOOK_URL}
      webhook-url-host: ${WEBHOOK_URL_HOST}
  --
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}-${ZONE}-backup-ftp
      labels:
        app: ${NAME}-${ZONE}
    type: Opaque
    stringData:
      ftp-url: ${FTP_URL}
      ftp-user: ${FTP_USER}
      ftp-password: ${FTP_PASSWORD}
      ftp-url-host: ${FTP_URL_HOST}
  --
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-spar-backend-network-security-policy
    spec:
      policyTypes:
        - Ingress
