apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: nr-spar
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: DB_PASSWORD
    description: Password for the PostgreSQL connection user
    required: true
  - name: FORESTCLIENTAPI_KEY
    required: true
  - name: ORACLE_HOST
    description: Oracle database host
    required: true
  - name: ORACLE_SERVICE
    description: Oracle service name
    value: dbq01.nrs.bcgov
  - name: ORACLE_PASSWORD
    description: Oracle database password for API
    required: true
  - name: ORACLE_USER
    description: Oracle database username for API
    value: proxy_fsa_spar_read_only_user
  - name: ORACLE_CERT_SECRET
    description: Oracle database keystore secret
    required: true
  - name: VITE_USER_POOLS_WEB_CLIENT_ID
    description: Cognito user pools web client ID
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-database
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-name: ${NAME}
      database-password: ${DB_PASSWORD}
      database-port: "5432"
      database-user: ${NAME}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-oracle-api
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      oracle-host: ${ORACLE_HOST}
      oracle-password: ${ORACLE_PASSWORD}
      oracle-service: ${ORACLE_SERVICE}
      oracle-user: ${ORACLE_USER}
      oracle-secret: ${ORACLE_CERT_SECRET}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-backend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      forest-client-api-key: ${FORESTCLIENTAPI_KEY}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-frontend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      vite-user-pools-web-client-id: ${VITE_USER_POOLS_WEB_CLIENT_ID}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-spar-backend-network-security-policy
    spec:
      policyTypes:
        - Ingress
