apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: nr-spar
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: PG_DATABASE
    description: Postgres database name
    value: database
  - name: DB_PASSWORD
    description: Password for the PostgreSQL connection user
    required: true
  - name: PG_DB_PORT
    description: Postgres database port
    value: "5432"
  - name: FORESTCLIENTAPI_KEY
    required: true
  - name: AWS_ACCESS_KEY_ID
    description: AWS Access Key ID
    required: true
  - name: AWS_ACCESS_KEY_SECRET
    description: AWS Access Key Secret
    required: true
  - name: AWS_KINESIS_STREAM
    description: AWS Kinesis stream name
    required: true
  - name: AWS_KINESIS_ROLE_ARN
    description: AWS Kinesis Role ARN
    required: true
  - name: ORACLE_HOST
    description: Oracle database host
    value: nrcdb03.bcgov
  - name: ORACLE_PORT
    description: Oracle database port
    value: "1543"
  - name: ORACLE_SERVICE
    description: Oracle service name
    value: dbq01.nrs.bcgov
  - name: ORACLE_DB_USER
    description: Oracle database username for API
    value: proxy_fsa_spar_read_only_user
  - name: ORACLE_DB_PASSWORD
    description: Oracle database password for API
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-${PG_DATABASE}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-name: ${NAME}
      database-password: ${DB_PASSWORD}
      database-port: ${PG_DB_PORT}
      database-user: ${NAME}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-oracle-api
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      oracle-host: ${ORACLE_HOST}
      oracle-password: ${ORACLE_DB_PASSWORD}
      oracle-port: ${ORACLE_PORT}
      oracle-service: ${ORACLE_SERVICE}
      oracle-user: ${ORACLE_DB_USER}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-backend
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      forest-client-api-key: ${FORESTCLIENTAPI_KEY}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-fluentbit
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      aws-access-key-id: ${AWS_ACCESS_KEY_ID}
      aws-access-key-secret: ${AWS_ACCESS_KEY_SECRET}
      aws-kinesis-stream: ${AWS_KINESIS_STREAM}
      aws-kinesis-role-arn: ${AWS_KINESIS_ROLE_ARN}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-spar-backend-network-security-policy
    spec:
      policyTypes:
        - Ingress
