INSERT INTO CORP_CAPTURE_METHOD (CAPTURE_METHOD_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('GPS', 'GPS', '1905-01-01', '9999-12-31');
INSERT INTO CORP_CAPTURE_METHOD (CAPTURE_METHOD_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('MAP', 'Map', '1905-01-01', '9999-12-31');

-- Not effective yet
INSERT INTO CORP_CAPTURE_METHOD (CAPTURE_METHOD_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('FUT', 'Future method', '2033-01-01', '2099-09-30');
-- Expired
INSERT INTO CORP_CAPTURE_METHOD (CAPTURE_METHOD_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('OLD', 'Expired method', '2002-01-01', '2022-09-30');
