-- Valid districts (ORG_UNIT_NO = ROLLUP_DIST_NO)
INSERT INTO ORG_UNIT (ORG_UNIT_NO, ORG_UNIT_CODE, ORG_UNIT_NAME, ROLLUP_DIST_NO, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES (45, 'DCC', 'Cariboo-Chilcotin Natural Resource District', 45, '1905-01-01', '9999-12-31');
INSERT INTO ORG_UNIT (ORG_UNIT_NO, ORG_UNIT_CODE, ORG_UNIT_NAME, ROLLUP_DIST_NO, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES (46, 'DPG', 'Prince George Natural Resource District', 46, '1905-01-01', '9999-12-31');

-- Non-district (rolls up to another unit, ORG_UNIT_NO != ROLLUP_DIST_NO)
INSERT INTO ORG_UNIT (ORG_UNIT_NO, ORG_UNIT_CODE, ORG_UNIT_NAME, ROLLUP_DIST_NO, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES (99, 'RCC', 'Cariboo Region', 45, '1905-01-01', '9999-12-31');

-- Not effective yet
INSERT INTO ORG_UNIT (ORG_UNIT_NO, ORG_UNIT_CODE, ORG_UNIT_NAME, ROLLUP_DIST_NO, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES (50, 'DFU', 'Future District', 50, '2033-01-01', '2099-09-30');

-- Expired
INSERT INTO ORG_UNIT (ORG_UNIT_NO, ORG_UNIT_CODE, ORG_UNIT_NAME, ROLLUP_DIST_NO, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES (51, 'DOL', 'Old District', 51, '2002-01-01', '2022-09-30');
