INSERT INTO SEED_COAST_AREA_CODE (SEED_COAST_AREA_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('N', 'North Coast', '1905-01-01', '9999-12-31');
INSERT INTO SEED_COAST_AREA_CODE (SEED_COAST_AREA_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('S', 'South Coast', '1905-01-01', '9999-12-31');

-- Not effective yet
INSERT INTO SEED_COAST_AREA_CODE (SEED_COAST_AREA_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('F', 'Future area', '2033-01-01', '2099-09-30');
-- Expired
INSERT INTO SEED_COAST_AREA_CODE (SEED_COAST_AREA_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE)
  VALUES ('X', 'Expired area', '2002-01-01', '2022-09-30');
