apiVersion: template.openshift.io/v1
kind: Template
parameters:
  ### Required - do not hard code
  - name: TAG
    description: Docker tag; e.g. PR-### or prod
    required: true
  - name: ZONE
    description: Deployment zone, e.g. pr-###, test or prod
    required: true

  ### Recommended - suggest hard coding
  - name: APP
    description: Application/component name
    value: sync
  - name: ORACLE_PORT
    description: Oracle database port
    value: "1543"
  - name: EXECUTION_ID
    description: Process execution ID for running ETL Tool
    value: "100"
  - name: ORG
    description: GitHub organization name
    value: bcgov
  - name: REPO
    description: Repository name
    value: nr-spar
  - name: TEST_MODE
    description: "Run in test mode"
    value: "false"

  ### Usually a bad idea - not recommended
  - name: JOB_BACKOFF_LIMIT
    description: "The number of attempts to try for a successful job outcome"
    value: "0"
  - name: JOB_HISTORY_FAIL
    description: "The number of failed jobs that will be retained"
    value: "1"
  - name: JOB_HISTORY_SUCCESS
    description: "The number of successful jobs that will be retained"
    value: "5"
  - name: REGISTRY
    description: Source container registry
    value: ghcr.io

objects:
  - kind: CronJob
    apiVersion: "batch/v1"
    metadata:
      name: ${REPO}-${ZONE}-${APP}
      labels:
        app: ${REPO}-${ZONE}
        cronjob: ${REPO}-${ZONE}
    spec:
      # 00:00 on day-of-month 1 in every 12000th month from January through December
      schedule: "0 0 1 1/12000 *" # https://crontab.guru/#0_0_1_1/12000_*
      startingDeadlineSeconds: 60
      concurrencyPolicy: "Replace"
      successfulJobsHistoryLimit: "${{JOB_HISTORY_SUCCESS}}"
      failedJobsHistoryLimit: "${{JOB_HISTORY_FAIL}}"
      jobTemplate:
        metadata:
          labels:
            app: ${REPO}-${ZONE}
            cronjob: ${REPO}-${ZONE}
        spec:
          backoffLimit: ${{JOB_BACKOFF_LIMIT}}
          template:
            metadata:
              labels:
                app: ${REPO}-${ZONE}
                cronjob: ${REPO}-${ZONE}
            spec:
              containers:
                - name: ${REPO}-${ZONE}
                  image: "${REGISTRY}/${ORG}/${REPO}/${APP}:${TAG}"
                  env:
                    - name: TEST_MODE
                      value: "${TEST_MODE}"
                    - name: EXECUTION_ID
                      value: "${EXECUTION_ID}"
                    - name: ORACLE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: ${REPO}-${ZONE}-sync
                          key: oracle-host
                    - name: ORACLE_SYNC_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${REPO}-${ZONE}-sync
                          key: oracle-sync-password
                    - name: ORACLE_PORT
                      value: ${ORACLE_PORT}
                    - name: ORACLE_SERVICE
                      valueFrom:
                        secretKeyRef:
                          name: ${REPO}-${ZONE}-sync
                          key: oracle-service
                    - name: ORACLE_SYNC_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${REPO}-${ZONE}-sync
                          key: oracle-sync-user
                    - name: POSTGRES_HOST
                      value: ${REPO}-${ZONE}-database
                    - name: POSTGRES_DB
                      valueFrom:
                        secretKeyRef:
                          name: ${REPO}-${ZONE}-database
                          key: database-name
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${REPO}-${ZONE}-database
                          key: database-password
                    - name: POSTGRES_PORT
                      valueFrom:
                        secretKeyRef:
                          name: ${REPO}-${ZONE}-database
                          key: database-port
                    - name: POSTGRES_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${REPO}-${ZONE}-database
                          key: database-user
                  resources:
                    limits:
                      cpu: 250m
                    requests:
                      cpu: 50m
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  imagePullPolicy: Always
              restartPolicy: Never
              terminationGracePeriodSeconds: 30
              activeDeadlineSeconds: 1600
              dnsPolicy: ClusterFirst
              serviceAccountName: pipeline
              schedulerName: default-scheduler

