package ca.bc.gov.backendstartapi.dto;

import java.math.BigDecimal;

public record SeedlotFormParentTreeSmpDto(
  Integer parentTreeId,
  String parentTreeNumber,
  String orchardId,
  String spu,
  BigDecimal coneCount,
  BigDecimal pollenCount,
  BigDecimal smpSuccessPerc,
  BigDecimal nonOrchardPollenContam,
  BigDecimal volume,
  BigDecimal proportion,
  BigDecimal ad,
  BigDecimal dfs,
  BigDecimal dfu,
  BigDecimal dfw,
  BigDecimal dsb,
  BigDecimal dsc,
  BigDecimal dsg,
  BigDecimal gvo,
  BigDecimal iws,
  BigDecimal wdu,
  BigDecimal wwd,
  BigDecimal w_ad,
  BigDecimal w_dfs,
  BigDecimal w_dfu,
  BigDecimal w_dfw,
  BigDecimal w_dsb,
  BigDecimal w_dsc,
  BigDecimal w_dsg,
  BigDecimal w_gvo,
  BigDecimal w_iws,
  BigDecimal w_wdu,
  BigDecimal w_wwd,
  BigDecimal meanDegLat,
  BigDecimal meanMinLat,
  BigDecimal meanDegLong,
  BigDecimal meanMinLong,
  BigDecimal meanElevation) {}
