CREATE SCHEMA IF NOT EXISTS CONSEP;

CREATE TABLE CONSEP.CNS_T_TSC_TEST_RESULT (
    RIA_SKEY DECIMAL(10, 0) PRIMARY KEY,
    ACTIVITY_TYPE_CD VARCHAR(3),
    STANDARD_TEST_IND INT,
    TEST_CATEGORY_CD VARCHAR(3),
    ACCEPT_RESULT_IND INT,
    TEST_COMPLETE_IND INT,
    ORIGINAL_TEST_IND INT,
    CURRENT_TEST_IND INT,
    TEST_RANK VARCHAR(1),
    SAMPLE_DESC VARCHAR(30),
    MOISTURE_STATUS_CD VARCHAR(3),
    GERMINATION_PCT INT,
    MOISTURE_PCT DECIMAL(4, 1),
    GERMINATION_VALUE INT,
    PEAK_VALUE_GRM_PCT INT,
    PEAK_VALUE_NO_DAYS INT,
    WEIGHT_PER_100 DECIMAL(7, 3),
    SEEDS_PER_GRAM INT,
    PURITY_PCT DECIMAL(4, 1),
    OTHER_TEST_RESULT DECIMAL(8, 3),
    UPDATE_TIMESTAMP DATE,
    STRAT_START_DT DATE,
    GERM_CNT_START_DT DATE,
    GERM_NEXT_STAGE_DT DATE,
    SEED_WITHDRAWAL_DATE DATE,
    WARM_STRAT_START_DATE DATE,
    DRYBACK_START_DATE DATE,
    GERMINATOR_ENTRY DATE,
    GERMINATOR_ID VARCHAR(1),
    GERMINATOR_TRAY_ID INT,
    LABEL_IND INT,
    RE_SAMPLE_IND INT
);

CREATE TABLE CONSEP.CNS_T_TEST_REP_GERM (
    RIA_SKEY DECIMAL(10, 0),
    TEST_REPLICATE_NO INT,
    TOTAL_NO_SEEDS INT,
    FINAL_UNGRM_NORMAL INT,
    FINAL_UNGRM_SHRVL INT,
    FINAL_UNGRM_EMPTY INT,
    FINAL_UNGRM_INSCT INT,
    FINAL_UNGRM_DAMAGD INT,
    FINAL_UNGRM_ROTTEN INT,
    FINAL_PREGERM INT,
    REP_ACCEPTED_IND INT,
    TOLRNC_OVRRDE_DESC VARCHAR(2000),
    PRIMARY KEY (RIA_SKEY, TEST_REPLICATE_NO)
);

CREATE SEQUENCE IF NOT EXISTS CONSEP.CNS_SEQ_COUNTER START WITH 1000 INCREMENT BY 1;

CREATE TABLE CONSEP.CNS_T_GERM_COUNT (
    RIA_SKEY DECIMAL(10, 0) PRIMARY KEY,
    DAILY_GERM_SKEY1 DECIMAL(10,0), COUNT_DT1 DATE, DAY_NO_OF_TEST1 DECIMAL(5,0), REP1_NO_SEEDS_GERM1 DECIMAL(5,0), REP2_NO_SEEDS_GERM1 DECIMAL(5,0), REP3_NO_SEEDS_GERM1 DECIMAL(5,0), REP4_NO_SEEDS_GERM1 DECIMAL(5,0), CUMULATIVE_GERM1 DECIMAL(7,4),
    DAILY_GERM_SKEY2 DECIMAL(10,0), COUNT_DT2 DATE, DAY_NO_OF_TEST2 DECIMAL(5,0), REP1_NO_SEEDS_GERM2 DECIMAL(5,0), REP2_NO_SEEDS_GERM2 DECIMAL(5,0), REP3_NO_SEEDS_GERM2 DECIMAL(5,0), REP4_NO_SEEDS_GERM2 DECIMAL(5,0), CUMULATIVE_GERM2 DECIMAL(7,4),
    DAILY_GERM_SKEY3 DECIMAL(10,0), COUNT_DT3 DATE, DAY_NO_OF_TEST3 DECIMAL(5,0), REP1_NO_SEEDS_GERM3 DECIMAL(5,0), REP2_NO_SEEDS_GERM3 DECIMAL(5,0), REP3_NO_SEEDS_GERM3 DECIMAL(5,0), REP4_NO_SEEDS_GERM3 DECIMAL(5,0), CUMULATIVE_GERM3 DECIMAL(7,4),
    DAILY_GERM_SKEY4 DECIMAL(10,0), COUNT_DT4 DATE, DAY_NO_OF_TEST4 DECIMAL(5,0), REP1_NO_SEEDS_GERM4 DECIMAL(5,0), REP2_NO_SEEDS_GERM4 DECIMAL(5,0), REP3_NO_SEEDS_GERM4 DECIMAL(5,0), REP4_NO_SEEDS_GERM4 DECIMAL(5,0), CUMULATIVE_GERM4 DECIMAL(7,4),
    DAILY_GERM_SKEY5 DECIMAL(10,0), COUNT_DT5 DATE, DAY_NO_OF_TEST5 DECIMAL(5,0), REP1_NO_SEEDS_GERM5 DECIMAL(5,0), REP2_NO_SEEDS_GERM5 DECIMAL(5,0), REP3_NO_SEEDS_GERM5 DECIMAL(5,0), REP4_NO_SEEDS_GERM5 DECIMAL(5,0), CUMULATIVE_GERM5 DECIMAL(7,4),
    DAILY_GERM_SKEY6 DECIMAL(10,0), COUNT_DT6 DATE, DAY_NO_OF_TEST6 DECIMAL(5,0), REP1_NO_SEEDS_GERM6 DECIMAL(5,0), REP2_NO_SEEDS_GERM6 DECIMAL(5,0), REP3_NO_SEEDS_GERM6 DECIMAL(5,0), REP4_NO_SEEDS_GERM6 DECIMAL(5,0), CUMULATIVE_GERM6 DECIMAL(7,4),
    DAILY_GERM_SKEY7 DECIMAL(10,0), COUNT_DT7 DATE, DAY_NO_OF_TEST7 DECIMAL(5,0), REP1_NO_SEEDS_GERM7 DECIMAL(5,0), REP2_NO_SEEDS_GERM7 DECIMAL(5,0), REP3_NO_SEEDS_GERM7 DECIMAL(5,0), REP4_NO_SEEDS_GERM7 DECIMAL(5,0), CUMULATIVE_GERM7 DECIMAL(7,4),
    DAILY_GERM_SKEY8 DECIMAL(10,0), COUNT_DT8 DATE, DAY_NO_OF_TEST8 DECIMAL(5,0), REP1_NO_SEEDS_GERM8 DECIMAL(5,0), REP2_NO_SEEDS_GERM8 DECIMAL(5,0), REP3_NO_SEEDS_GERM8 DECIMAL(5,0), REP4_NO_SEEDS_GERM8 DECIMAL(5,0), CUMULATIVE_GERM8 DECIMAL(7,4),
    DAILY_GERM_SKEY9 DECIMAL(10,0), COUNT_DT9 DATE, DAY_NO_OF_TEST9 DECIMAL(5,0), REP1_NO_SEEDS_GERM9 DECIMAL(5,0), REP2_NO_SEEDS_GERM9 DECIMAL(5,0), REP3_NO_SEEDS_GERM9 DECIMAL(5,0), REP4_NO_SEEDS_GERM9 DECIMAL(5,0), CUMULATIVE_GERM9 DECIMAL(7,4),
    DAILY_GERM_SKEY10 DECIMAL(10,0), COUNT_DT10 DATE, DAY_NO_OF_TEST10 DECIMAL(5,0), REP1_NO_SEEDS_GERM10 DECIMAL(5,0), REP2_NO_SEEDS_GERM10 DECIMAL(5,0), REP3_NO_SEEDS_GERM10 DECIMAL(5,0), REP4_NO_SEEDS_GERM10 DECIMAL(5,0), CUMULATIVE_GERM10 DECIMAL(7,4),
    DAILY_GERM_SKEY11 DECIMAL(10,0), COUNT_DT11 DATE, DAY_NO_OF_TEST11 DECIMAL(5,0), REP1_NO_SEEDS_GERM11 DECIMAL(5,0), REP2_NO_SEEDS_GERM11 DECIMAL(5,0), REP3_NO_SEEDS_GERM11 DECIMAL(5,0), REP4_NO_SEEDS_GERM11 DECIMAL(5,0), CUMULATIVE_GERM11 DECIMAL(7,4),
    DAILY_GERM_SKEY12 DECIMAL(10,0), COUNT_DT12 DATE, DAY_NO_OF_TEST12 DECIMAL(5,0), REP1_NO_SEEDS_GERM12 DECIMAL(5,0), REP2_NO_SEEDS_GERM12 DECIMAL(5,0), REP3_NO_SEEDS_GERM12 DECIMAL(5,0), REP4_NO_SEEDS_GERM12 DECIMAL(5,0), CUMULATIVE_GERM12 DECIMAL(7,4),
    DAILY_GERM_SKEY13 DECIMAL(10,0), COUNT_DT13 DATE, DAY_NO_OF_TEST13 DECIMAL(5,0), REP1_NO_SEEDS_GERM13 DECIMAL(5,0), REP2_NO_SEEDS_GERM13 DECIMAL(5,0), REP3_NO_SEEDS_GERM13 DECIMAL(5,0), REP4_NO_SEEDS_GERM13 DECIMAL(5,0), CUMULATIVE_GERM13 DECIMAL(7,4),
    ENTRY_USERID VARCHAR(30), ENTRY_TIMESTAMP TIMESTAMP, UPDATE_USERID VARCHAR(30), UPDATE_TIMESTAMP TIMESTAMP
);

CREATE TABLE CONSEP.CNS_T_DAILY_ABNORMAL (
    DAILY_GERM_SKEY DECIMAL(10, 0) PRIMARY KEY,
    RP1_NO_ABNRM_RE DECIMAL(5,0), RP1_NO_ABNRM_SR DECIMAL(5,0), RP1_NO_ABNRM_SH DECIMAL(5,0), RP1_NO_ABNRM_RN DECIMAL(5,0), RP1_NO_ABNRM_TH DECIMAL(5,0), RP1_NO_ABNRM_TR DECIMAL(5,0), RP1_NO_ABNRM_TW DECIMAL(5,0), RP1_NO_ABNRM_CM DECIMAL(5,0), RP1_NO_ABNRM_WEAK DECIMAL(5,0), RP1_NO_ABNRM_OTHER DECIMAL(5,0), RP1_NO_ABNRM_PRGRM DECIMAL(5,0),
    RP2_NO_ABNRM_RE DECIMAL(5,0), RP2_NO_ABNRM_SR DECIMAL(5,0), RP2_NO_ABNRM_SH DECIMAL(5,0), RP2_NO_ABNRM_RN DECIMAL(5,0), RP2_NO_ABNRM_TH DECIMAL(5,0), RP2_NO_ABNRM_TR DECIMAL(5,0), RP2_NO_ABNRM_TW DECIMAL(5,0), RP2_NO_ABNRM_CM DECIMAL(5,0), RP2_NO_ABNRM_WEAK DECIMAL(5,0), RP2_NO_ABNRM_OTHER DECIMAL(5,0), RP2_NO_ABNRM_PRGRM DECIMAL(5,0),
    RP3_NO_ABNRM_RE DECIMAL(5,0), RP3_NO_ABNRM_SR DECIMAL(5,0), RP3_NO_ABNRM_SH DECIMAL(5,0), RP3_NO_ABNRM_RN DECIMAL(5,0), RP3_NO_ABNRM_TH DECIMAL(5,0), RP3_NO_ABNRM_TR DECIMAL(5,0), RP3_NO_ABNRM_TW DECIMAL(5,0), RP3_NO_ABNRM_CM DECIMAL(5,0), RP3_NO_ABNRM_WEAK DECIMAL(5,0), RP3_NO_ABNRM_OTHER DECIMAL(5,0), RP3_NO_ABNRM_PRGRM DECIMAL(5,0),
    RP4_NO_ABNRM_RE DECIMAL(5,0), RP4_NO_ABNRM_SR DECIMAL(5,0), RP4_NO_ABNRM_SH DECIMAL(5,0), RP4_NO_ABNRM_RN DECIMAL(5,0), RP4_NO_ABNRM_TH DECIMAL(5,0), RP4_NO_ABNRM_TR DECIMAL(5,0), RP4_NO_ABNRM_TW DECIMAL(5,0), RP4_NO_ABNRM_CM DECIMAL(5,0), RP4_NO_ABNRM_WEAK DECIMAL(5,0), RP4_NO_ABNRM_OTHER DECIMAL(5,0), RP4_NO_ABNRM_PRGRM DECIMAL(5,0)
);