name: Cypress Nightly

on:
  schedule:
    # runs e2e tests every day at 4am
    - cron: '0 4 * * *'

jobs:
  e2e-chrome:
    runs-on: ubuntu-20.04
    name: E2E on Google Chrome
    env:
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: frontend/cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos-chrome
          path: frontend/cypress/videos
  
  e2e-firefox:
    runs-on: ubuntu-20.04
    container:
      image: cypress/included:11.2.0
      options: --user 1001
    name: E2E on Mozilla Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        run: cypress run --browser firefox
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-firefox
          path: frontend/cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos-firefox
          path: frontend/cypress/videos

  e2e-edge:
    runs-on: windows-latest
    name: E2E on Microsoft Edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: edge
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-edge
          path: frontend/cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos-edge
          path: frontend/cypress/videos
