name: Cypress Nightly

on:
  workflow_dispatch:
  schedule:
    # runs e2e tests every day at 4am
    - cron: '0 4 * * *'

jobs:
  tests:
    name: Tests
    needs: [deploys]
    secrets: inherit
    uses: ./.github/workflows/.tests.yml
    with:
      target: test
