name: Database Backups

on:
  schedule: [cron: "11 18 * * *"] # 6:11 PM GMT = 1:11 AM PST
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  db-bk-test:
    environment: test
    name: Database Backup (TEST)
    continue-on-error: true
    runs-on: ubuntu-24.04
    steps:
      - uses: bcgov/action-oc-runner@10033668ef4374d9bb78149faa73e4ccda0e93dd # v1.2.3
        with:
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          commands: ./common/db_bk_run.sh test

  db-bk-prod:
    environment: prod
    name: Database Backup (PROD)
    continue-on-error: false
    runs-on: ubuntu-24.04
    steps:
      - uses: bcgov/action-oc-runner@10033668ef4374d9bb78149faa73e4ccda0e93dd # v1.2.3
        with:
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          commands: ./common/db_bk_run.sh prod
