name: ETL TEST

on:
  schedule: [cron: "0 */2 * * *"] # Every other hour on the hour
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  etl-test:
    environment: test
    name: ETL (TEST)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"
      - name: Run ./sync/oc_run.sh
        run: ./sync/oc_run.sh test ${{ secrets.oc_token }}
