name: ETL Sync

on:
  schedule: [cron: "0 */2 * * *"] # Every other hour on the hour
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  sync-test:
    environment: test
    name: Sync (TEST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"
      - name: ETL (TEST)
        run: ./sync/oc_run.sh test ${{ secrets.oc_token }}

  sync-prod:
    environment: prod
    name: Sync (PROD)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"
      - name: ETL (PROD)
        run: ./sync/oc_run.sh prod ${{ secrets.oc_token }}
