name: ETL Sync

on:
  schedule: [cron: "0 */2 * * *"] # Every other hour on the hour
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Override OpenShift version
        env:
          OC: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.13/openshift-client-linux.tar.gz
        run: |
          # Download and extract with retry, continuing on error
          (wget ${{ env.OC }} -qcO - | tar -xzvf - oc)|| !! || true
          oc version
        working-directory: /usr/local/bin/

      - name: ETL Sync
        run: ./sync/oc_run.sh test ${{ secrets.oc_token }}
